In [3]:
import numpy as np
from sklearn.decomposition import FastICA
S=np.array([[1,1],
           [2,-1],
           [3,1],
           [4,-1]])
A=np.array([[1,2],
           [3,4]])
X=S @ A.T
#Apply ICA
ica=FastICA(n_components=2,random_state=0)
U=ica.fit_transform(X)
print('Orig Source:\n',S)
print("Recovered Sources(Approx):\n",U)

Orig Source:
 [[ 1  1]
 [ 2 -1]
 [ 3  1]
 [ 4 -1]]
Recovered Sources(Approx):
 [[-1.  1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1. -1.]]


In [13]:
import numpy as np
from sklearn.neural_network import MLPRegressor
X=np.array([[1,2,3,4],
           [2,3,4,5],
           [3,4,5,6],
           [4,5,6,7]],dtype=float)
autoencoder=MLPRegressor(hidden_layer_sizes=(2,),activation="relu",max_iter=5000,random_state=0)
autoencoder.fit(X,X)
X_reconstructed=autoencoder.predict(X)
w=autoencoder.coefs_[0]
b=autoencoder.intercepts_[0]
hidden_2d=np.maximum(0, X @ w + b)
print('Orig Source:\n',X)
print("\nHidden (2 features) \n",np.round(hidden_2d, 2))
print("Reconstructed (4 features):\n",X_reconstructed)

Orig Source:
 [[1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]
 [4. 5. 6. 7.]]

Hidden (2 features) 
 [[4.35 1.56]
 [5.81 2.11]
 [7.27 2.66]
 [8.74 3.21]]
Reconstructed (4 features):
 [[2.05115267 2.76352408 3.40485058 3.99349928]
 [2.51840678 3.32560192 4.09382216 4.99717406]
 [2.98566088 3.88767976 4.78279373 6.00084883]
 [3.45291499 4.44975761 5.47176531 7.00452361]]
