In [1]:
import numpy as np
from sklearn.decomposition import FastICA
S=np.array([[1,1],
           [2,-1],
           [3,1],
           [4,-1]])
A=np.array([[1,2],
           [3,4]])
X=S @ A.T
#Apply ICA
ica=FastICA(n_components=2,random_state=0)
U=ica.fit_transform(X)
print('Orig Source:\n',S)
print("Recovered Sources(Approx):\n",U)

Orig Source:
 [[ 1  1]
 [ 2 -1]
 [ 3  1]
 [ 4 -1]]
Recovered Sources(Approx):
 [[-1.  1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1. -1.]]


In [2]:
import numpy as np
from sklearn.neural_network import MLPRegressor
X=np.array([[1,2,3,4],
           [2,3,4,5],
           [3,4,5,6],
           [4,5,6,7]],dtype=float)
autoencoder=MLPRegressor(hidden_layer_sizes=(2,),activation="relu",max_iter=5000,random_state=0)
autoencoder.fit(X,X)
X_reconstructed=autoencoder.predict(X)
w=autoencoder.coefs_[0]
b=autoencoder.intercepts_[0]
hidden_2d=np.maximum(0, X @ w + b)
print('Orig Source:\n',X)
print("\nHidden (2 features) \n",np.round(hidden_2d, 2))
print("Reconstructed (4 features):\n",X_reconstructed)

Orig Source:
 [[1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]
 [4. 5. 6. 7.]]

Hidden (2 features) 
 [[4.35 1.56]
 [5.81 2.11]
 [7.27 2.66]
 [8.74 3.21]]
Reconstructed (4 features):
 [[2.05115267 2.76352408 3.40485058 3.99349928]
 [2.51840678 3.32560192 4.09382216 4.99717406]
 [2.98566088 3.88767976 4.78279373 6.00084883]
 [3.45291499 4.44975761 5.47176531 7.00452361]]


In [3]:
import numpy as np
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
x,y=make_classification(n_samples=100,
                       n_features=2,
                       n_redundant=0,
                       n_informative=2,
                       random_state=0)
labeled=np.arange(10)
unlabeled=np.arange(10,100)
model=LogisticRegression(solver="liblinear")

for i in range(5):
    model.fit(x[labeled],y[labeled])
    probs=model.predict_proba(x[unlabeled])[:,1]
    query=np.argmin(np.abs(probs-0.5))
    labeled=np.append(labeled,unlabeled[query])
    unlabeled=np.delete(unlabeled,query)
    print("Iteration:",i+1, "|Labeled size:",len(labeled))


Iteration: 1 |Labeled size: 11
Iteration: 2 |Labeled size: 12
Iteration: 3 |Labeled size: 13
Iteration: 4 |Labeled size: 14
Iteration: 5 |Labeled size: 15


In [4]:
import numpy as np
X=np.array([[1],[2],[3],[4]])
y=np.array([0,0,1,1])
centers=np.array([[1],[4]])
sigma=1.0

#Gaussian RBF fun
def rbf(x,c):
    return np.exp(-np.linalg.norm(x-c)**2 /(2*sigma**2))
H=np.array([[rbf(x,c) for c in centers] for x in X])

w=np.linalg.pinv(H)@y
y_pred=H@w
y_pred_class=(y_pred >0.5).astype(int)
print("Predicted:",y_pred_class)

Predicted: [0 0 1 1]


In [5]:
trans=[
    {"A","B"},
    {"A","C"},
    {"B","C"},
    {"A","B"},
]
min_sup=2
tid={}
for i,t in enumerate(trans):
    for item in t:
        if item not in tid:
            tid[item]=set()
    tid[item].add(i)
print("TID Lists:",tid)
AB=tid["A"]&tid["B"] #core idea op eclat
print("Support of (A,B):",len(AB))
if len(AB) >= min_sup:
    print("A,B is frequent")

TID Lists: {'A': set(), 'B': {0, 3}, 'C': {1, 2}}
Support of (A,B): 0


In [7]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.metrics import accuracy_score

X,y=make_classification(n_samples=500,n_features=5,random_state=0)
Xtr,Xte,ytr,yte=train_test_split(X,y,test_size=0.3,random_state=0)
bag=BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimator=20,
    bootstrap=True,
    random_state=0   
)
bag.fit(Xtr,ytr)
print(" Bagging accuracy:",accuracy_score(yte,bag.predict(Xte)))

TypeError: BaggingClassifier.__init__() got an unexpected keyword argument 'n_estimator'

In [8]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.metrics import accuracy_score


X, y = make_classification(n_samples=500, n_features=5, random_state=0)

Xtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.3, random_state=0)

bag = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=20,  
    bootstrap=True,
    random_state=0
)

bag.fit(Xtr, ytr)

print("Bagging accuracy:", accuracy_score(yte, bag.predict(Xte)))

Bagging accuracy: 0.9133333333333333


In [9]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
ada=AdaBoostClassifier(
     estimator=DecisionTreeClassifier(max_depth=1),
    n_estimators=50,
    learning_rate=1.0,
    random_state=0
)
ada.fit(xtr,ytr)
print("AdaBoost accuracy : ",accuracy_score(yte,ada.predict(xte)))

NameError: name 'xtr' is not defined